[tox]
envlist = 3.10, 3.11, 3.12, 3.13, 3.14, docs, packaging

[testenv]
commands =
    pytest libtaxii
    sphinx-build -b doctest docs docs/_build/doctest
    sphinx-build -b html docs docs/_build/html
deps = -rrequirements.txt

[testenv:docs]
commands =
    sphinx-build -b doctest docs docs/_build/doctest
    sphinx-build -b html docs docs/_build/html

[testenv:packaging]
deps =
    readme_renderer
    setuptools
commands =
    python setup.py check -r -s

[travis]
python =
  3.10: 3.10
  3.11: 3.11
  3.12: 3.12
  3.13: 3.13
  3.14: 3.14, docs, packaging
